# Site settings
baseurl = "http://artlang.net/"
languageCode = "ru-ru"
title = "Artlang: Programming Blog"
theme = "cactus"
paginate = 4

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable comments by leaving disqusShortname empty
# disqusShortname = "artlangnet"

[params]
	name = "Artlang"
	description = "Artlang: Programming Blog. Articles, projects, about, contacts"
	bio = "Programming Blog"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/style-ext.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "Some rights reserved, 2018 - <a href='/'>Artlang</a> - Powered by <a href='https://gohugo.io'>Hugo</a>"

	# Sharing options and author information in posts
	aboutAuthor = "Programming Blog"
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"

    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    # twitter  = "https://www.twitter.com/"
    # facebook = "https://www.facebook.com/"
    # github   = "https://www.github.com/"
    # dribble  = "https://www.dribbble.com/"